### ISSUE TITLE
Can't create new Pull Requests

### ISSUE THREAD

**Issue by yuriron** [MistyKuu/bitbucket-for-visual-studio#80]
We use Visual Studio 17 (various builds, some updated and some not) and ilately we can't create new Pull Requests from the extension - only view & update existing ones. Once we press the big plus sign, we see an "Invalid page" error message right below the "Create New Pull Request" header. Uninstalling & reinstalling the extension didn't help. 

![image](https://user-images.githubusercontent.com/39796478/44404217-181f9800-a55f-11e8-9fab-20c5c5ab4ef9.png)

**Comment by MistyKuu** [comment]
Fixed here https://github.com/MistyKuu/bitbucket-for-visual-studio/commit/36a6d1efde3f324d1e719a0e647de582245e34c9. I will release soon in 1.38 version.

**Comment by yuriron** [comment]
Still happening even after upgrading to the new 1.37.9 release (which is surprisingly higher than the 1.37.8 which is the highest currently displayed in GitHub)...

![image](https://user-images.githubusercontent.com/39796478/44425614-048f2400-a595-11e8-8cdf-238a3e8ec0ba.png)

**Comment by MistyKuu** [comment]
It's 1.37.9. I've just upgraded and it seems to work. Is it official bitbucket or your private one?
![image](https://user-images.githubusercontent.com/10333668/44427411-ce03da00-a591-11e8-8019-1d158aa0bb6a.png)

**Comment by yuriron** [comment]
Sorry for my late response - it's Bitbucket Cloud with private repositories. I asked several users (with various VS2017 builds) to upgrade and none managed to create a PR (on various repositories), all faced the same error massage. Is there a log I can provide you with some debug details? 

BTW, for some this new version also introduced an issue with the GitHub extension (see attached). 

[ActivityLog.zip](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2315476/ActivityLog.zip)

**Comment by mgwillett** [comment]
We are running VS2017 v15.9.7 with Bitbucket Extension v1.40.1; trying to create new pull requests shows the same "Invalid page" error message from the top of this thread. Has the issue been reintroduced or hopefully fixed in soon to be released version? Thank you.
